"""followers

Revision ID: 18741afe9a17
Revises: 39aa4139a3cc
Create Date: 2021-02-02 11:21:22.387691

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18741afe9a17'
down_revision = '39aa4139a3cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
