"""new fields in user model

Revision ID: 39aa4139a3cc
Revises: dbbeec758437
Create Date: 2021-02-02 09:46:48.505764

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39aa4139a3cc'
down_revision = 'dbbeec758437'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
